project:
  type: manuscript

manuscript:
  article: index.qmd

format:
  apaquarto-docx:
    toc: false
  apaquarto-html:
    toc: true
    # apaquarto-typst:
    #   keep-typ: true
    #   list-of-figures: false
    #   list-of-tables: false
    #   toc: false
    papersize: "us-letter"
  # apaquarto-pdf:
  #   # Can be jou (journal), man (manuscript), stu (student), or doc (document)
  #   documentmode: jou
  #   keep-tex: true
  jats: default
  # html:
  #   comments:
  #     hypothesis: true
  typst:
    keep-typ: true
  # docx: default

execute:
  freeze: true
